### ISSUE TITLE
sublisting - paging

### ISSUE THREAD

**Issue by Pako2** [RomanSmolka/plugin.video.iprima#1]
Ahoj.
Provozuji Kodi na Orange Pi Lite 2 a Orange Pi PC.
Pro tyto desky neexistují stabilní verze, pouze "night builds", tedy Kodi 19 (Matrix).
Protože pro Kodi 19 jsem nenašel skoro žádné doplňky, pustil jsem se do úprav doplňků pro Kodi 18.
Jedním z nich je také doplněk "iPrima.cz".
Při úpravě jsem narazil na chybu. Nefungovalo stránkování sublistingu.
Chyba je ve skriptu plugin.py na řádce 112:
Místo 
`plugin.url_for_path( '/sublisting/{0}/?season={1}&page={2}'.format(programId, season, page+1) ),`
musí být
`plugin.url_for_path( '/sublisting/{0}/{1}?page={2}'.format(programId, season, page+1) ),`

listener
(to je můj nick ve fóru XBMC-Kodi CZ/SK)

**Comment by RomanSmolka** [comment]
Díky moc, opraveno v nové verzi 1.1.2
