### ISSUE TITLE
Možnost přihlášení uživatele do iprima.cz

### ISSUE THREAD

**Issue by JohnnyEn** [RomanSmolka/plugin.video.iprima#2]
Prima poslední dobou uzavírá víc zajímavých pořadů pod přihlášení. Bude možné udělat autorizaci uživatele?

**Comment by RomanSmolka** [comment]
Přihlašování bylo přidáno ve verzi 1.3.0

**Comment by JohnnyEn** [comment]
@RomanSmolka Aha, to znamená, že mi na mediacentru vykysla nějaká historická verze. Díky moc za info, plugin a zavírám.
