### ISSUE TITLE
Nefunkcni doplnek po zmene na PrimaPlus

### ISSUE THREAD

**Issue by jirkav77** [RomanSmolka/plugin.video.iprima#9]
Zmenil se zpusob prihlasovani (navic je tam volba profilu), tento problem lze vyresit nasledujici zmenou v auth.py

	# Acquire prima ProfileID
	r_profile_id = re.search('data-identifier="(.*)"', do_login.text)
	profile_id = r_profile_id.group(1)	
	cookies = {
		'prima_device_id': device_id,
		'prima_sso_profile': profile_id
	}
	# Auth with ProfileID
	do_auth = s.get('https://auth.iprima.cz/oauth2/authorize?response_type=code&client_id=prima_sso&redirect_uri=https://auth.iprima.cz/sso/auth-check&scope=openid email profile phone address offline_access&state=prima_sso&auth_init_url=https://www.iprima.cz/&auth_return_url=https://www.iprima.cz/?authentication=cancelled', cookies=cookies, allow_redirects=False)
	# Acquire authorization code from login result
	parsed_auth_url = urlparse(do_auth.headers['Location'])

Druhy problem je zda se v lookup.py, kde je potreba pridat hodnotu
`free_admittance_types = ['free', 'basic', 'registered', 'catchup']`

Uvedene upravy nejsou 100%, proto neposilam pull request, ale jako hotfix to vypada funkcni.  Neresi to vice uzivatelskych profilu a dalsi mozne zmeny v API.

**Comment by johny-mnemonic** [comment]
Mám stejný problém a změna kódu výše ho zdá se řeší. Díky!
Takže @jirkav77 vůbec se nestyď a udělej PR. Bez něj je to trocha věštění s křišťálovou koulí, kam že má člověk ty změny vlastně dát ;-)
A vzhledem k tomu, že @RomanSmolka na fóru psal, že na to teď nemá čas, tak mu určitě přijde vhod PR připravený k otestování a případnému zamergování.

**Comment by RomanSmolka** [comment]
Mělo by být vyřešeno v nové verzi 1.4.3, kde jsou zamergované PR #8 a #10
